sudo: required
dist: trusty
language: scala
scala:
- 2.11.8
addons:
  apt:
    packages:
    - realpath
    - chromium-chromedriver
    - xvfb
    - texlive
    - lmodern
    - texlive-generic-recommended
    - cabal-install
    - ghc
before_install:
- openssl aes-256-cbc -K $encrypted_a9e8fd99858b_key -iv $encrypted_a9e8fd99858b_iv
  -in travis.key.enc -out ~/.ssh/id_rsa -d
- sudo cabal update
- sudo cabal install Cabal cabal-install -j10 --global
- sudo cabal install pandoc -j10 -f -https -f -network-uri --force-reinstalls --global
- curl https://sh.rustup.rs -sSf > rustup.sh
- sh rustup.sh -y
- export PATH=~/.cargo/bin:$PATH
- createdb wilcd
- wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz
- tar xvf libsodium-1.0.12.tar.gz
- pushd libsodium-1.0.12
- "./configure"
- make
- sudo make install
- popd
- sudo cp wilcd-ui/chromedriver.sh /usr/local/bin/chromedriver
script:
- pushd binfontify
- cargo test
- popd
- pushd Prototyp-teo
- mv Src/font.c Src/font-git.c
- "./regen-font.sh"
- cmp Src/font.c Src/font-git.c
- popd
- pushd uartd
- cargo test
- popd
- pushd wilcd-ui
- xvfb-run env LD_LIBRARY_PATH=/usr/lib/chromium-browser/libs sbt test
- popd
deploy:
  provider: script
  script: "./travis-deploy.sh"
  on:
    branch: master
