#!/usr/bin/env bash
DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))
TARGET="$DIR/Src/font.c"
cd "$DIR/../binfontify"
cat > $TARGET <<EOF
/* GENERATED BY binfontify, DO NOT MODIFY */

EOF

cargo run --release WiLCD-Sans.txt >> $TARGET
