#!/usr/bin/env bash
DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))
TARGET="$DIR/Src/font.c"
cd "$DIR/../../binfontify"
cat > $TARGET <<EOF
/* GENERATED BY binfontify, DO NOT MODIFY!!
 * Instead, modify binfontify/WiLCD-Sans.txt
 * and then rerun regen-font.sh
 */

#include "font.h"

EOF

cargo run --release WiLCD-Sans.txt >> $TARGET
