* Risker
  :PROPERTIES:
  :CUSTOM_ID: risker
  :END:

Följande risker anses finnas under detta projekt:

1. Sjukdom och olyckor

2. Prototyper fås ej att fungera eller på ett realistiskt sätt emulera
   en slutgiltig produkt

3. Beställd hårdvara levereras ej inom angiven tid eller är defekt vid
   mottagande

4. Designat PCB visas sig ha önskad funktionalitet eller har defekter i
   designen.

5. Valda hård- och mjuk-varulösningar blir ej implementerade på grund av
   tids- eller kompetens-brist

* Riskprevention
  :PROPERTIES:
  :CUSTOM_ID: riskprevention
  :END:

För att undvika dessa risker så kommer följande att göras:

1. Genom att dagligen ha avstämningsmöten vet alla vad som behövs göra
   och kompetensen är spridd så de flesta uppgifter kan utföras av minst
   två personer. Detta förhindrar större förseningar på grund av
   bortfall av arbetstimmar.

2. Genom noggrann planering och specifika slices och task delas
   projektet upp i kritiska delar som krävs för att få ett fungerande
   grundsystem.

3. Beställningar sker enbart via kända och beprövade källor, defekter
   vid leverans finns det tyvärr ingen möjlighet att skydda sig mot på
   grund av en begränsad budget

4. PCB-designen gås igenom noggrant av både gruppens medlemmar och en
   extern part som sedan skickar PCB-designen till tillverkning.

5. Som punkterna 1 och 2 säger så är planeringen för projektet och varje
   sprint gjord för att förhindra problem av tidsrelaterad karaktär.


